sudo: required
language: ruby
rvm:
  - 2.2.6
  - 2.3.1

services:
  - docker

cache:
  bundler: true
  directories:
    - node_modules
  yarn: true

install:
  - nvm install node
  - node -v
  - npm i -g yarn@0.20.3
  - yarn

script:
  - node_modules/eslint/bin/eslint.js lib/
